Repository Inist-CNRS/tdm-factory, pull requests merged in 2025-05, with the labels that each got.

#95 fix: csv enrichment works now
  tdm-be/config/development.json
  tdm-be/src/controller/traitment.ts
  tdm-fe/src/app/components/form/ProcessingFormConfiguration.tsx
  tdm-fe/src/app/components/form/ProcessingFormUpload.tsx
  tdm-fe/src/app/pages/ProcessingCreationForm.tsx
  tdm-fe/src/app/services/creation/processing.ts
Labels: bug, ready to merge

#98 fix: removed completely the return button at confirmation step
  tdm-fe/src/app/pages/ProcessingCreationForm.tsx
Labels: bug

#102 fix: replaced tm tools link and removed the "Commencer un traitement"…
  tdm-fe/src/app/components/layout/Header.tsx
  tdm-fe/src/app/components/layout/ServiceDescription.tsx
Labels: ready to merge

#100 feat: added download button at final step
  tdm-be/src/app.ts
  tdm-be/src/controller/traitment.ts
  tdm-be/src/worker/enrichmentHook.ts
  tdm-be/src/worker/wrapper.ts
  tdm-fe/src/app/App.tsx
  tdm-fe/src/app/components/form/ProcessingFormConfiguration.tsx
  tdm-fe/src/app/components/form/ProcessingFormConfirmation.tsx
  tdm-fe/src/app/components/form/ProcessingFormUpload.tsx
  tdm-fe/src/app/components/form/scss/ProcessingFormConfirmation.scss
  tdm-fe/src/app/pages/ProcessingCreationForm.tsx
  tdm-fe/src/app/pages/ProcessingStatus.tsx
  tdm-fe/src/app/services/Environment.ts
  tdm-fe/src/app/services/processing/processing-info.ts
  tdm-fe/src/app/services/result/result.ts
  tdm-fe/src/app/shared/data.types.ts
  tdm-fe/src/app/shared/routes.ts
Labels: ready to merge

#105 Fix selection of a flow with another flow having the same enricher
  tdm-fe/src/app/components/form/ProcessingFormConfiguration.tsx
  tdm-fe/src/app/pages/ProcessingCreationForm.tsx
  tdm-fe/src/app/shared/data.types.ts
Labels: bug

#106 Fix enrichment conversion
  tdm-be/config/production.json
  tdm-fe/src/app/components/form/ProcessingFormConfiguration.tsx
Labels: bug

#108 Fix static config cache
  tdm-be/config/production.json
  tdm-fe/src/app/components/form/ProcessingFormConfiguration.tsx
Labels: bug

#109 Update config
  tdm-be/config/development.json
  tdm-be/config/production.json
Labels: config

#110 Add teeft and rename tag cloud
  tdm-be/config/development.json
  tdm-be/config/production.json
Labels: config
