Repository Inist-CNRS/tdm-factory, pull requests merged in 2025-07, with the labels that each got.

#131 feat: replaced "ANR Fundings" with "Operated by Inist-CNRS"
  tdm-fe/public/logo/investissement.png
  tdm-fe/public/logo/opere_par_inist.svg
  tdm-fe/src/app/components/layout/Footer.tsx
  tdm-fe/src/app/components/layout/scss/Footer.scss
Labels: ready to merge

#130 fix: enrichment are selected with id instead of link
  tdm-fe/public/logo/investissement.png
  tdm-fe/public/logo/opere_par_inist.svg
  tdm-fe/src/app/components/form/ProcessingFormConfiguration.tsx
  tdm-fe/src/app/components/layout/Footer.tsx
  tdm-fe/src/app/components/layout/scss/Footer.scss
Labels: ready to merge

#133 Remove enrichment & wrappers from dynamic config
  tdm-be/bin/swagger.ts
  tdm-be/src/app.ts
  tdm-be/src/controller/config.ts
  tdm-be/src/controller/data-enrichment.ts
  tdm-be/src/controller/data-wrapper.ts
  tdm-be/src/controller/traitment.ts
  tdm-be/src/model/DynamicConfig.ts
  tdm-be/src/model/Traitment.ts
  tdm-be/src/model/json/DefaultDynamicConfig.json
  tdm-be/src/swagger/swagger-config.json
  tdm-be/src/worker/enrichmentHook.ts
  tdm-fe/src/app/components/form/ProcessingFormConfiguration.tsx
  tdm-fe/src/app/pages/ProcessingCreationForm.tsx
  tdm-fe/src/app/services/Environment.ts
  tdm-fe/src/app/services/creation/operations.ts
  tdm-fe/src/app/services/creation/processing.ts
  tdm-fe/src/app/shared/data.types.ts
Labels: enhancement

#134 Add end-to-end tests using Playwright
  .vscode/extensions.json
  .vscode/settings.json
  tdm-fe/.gitignore
  tdm-fe/README.md
  tdm-fe/TESTING.md
  tdm-fe/package-lock.json
  tdm-fe/package.json
  tdm-fe/playwright.config.ts
  tdm-fe/tests/e2e/.gitignore
  tdm-fe/tests/e2e/README.md
  tdm-fe/tests/e2e/fixtures/istex.tar.gz
  tdm-fe/tests/e2e/fixtures/test-data.ts
  tdm-fe/tests/e2e/fixtures/txt-teeft-fr.txt
  tdm-fe/tests/e2e/global-setup.ts
  tdm-fe/tests/e2e/global-teardown.ts
  tdm-fe/tests/e2e/helpers/api-helpers.ts
  tdm-fe/tests/e2e/helpers/file-helpers.ts
  tdm-fe/tests/e2e/helpers/ui-helpers.ts
  tdm-fe/tests/e2e/specs/admin-interface.spec.ts
  tdm-fe/tests/e2e/specs/example.spec.ts
  tdm-fe/tests/e2e/specs/file-upload.spec.ts
  tdm-fe/tests/e2e/specs/navigation.spec.ts
  tdm-fe/tests/e2e/specs/processing-workflow.spec.ts
Labels: test
